blank_issues_enabled: false
contact_links:
  - name: Security vulnerability
    url: https://github.com/SrivatsaRv/vector-engagements-labs/security/advisories/new
    about: Report vulnerabilities privately
