"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import {
  ArrowLeft, Check, CircleAlert, CircleHelp,
  Copy, Eye, EyeOff, FileText, Flag, Gauge, Layers3,
  Pause, Play, RotateCcw, Save, Settings2, ShieldCheck,
  Sparkles, Target, TriangleAlert,
} from "lucide-react";
import { SimulationScene } from "@/components/SimulationScene";
import { TelemetryChart } from "@/components/TelemetryChart";
import { LabHome } from "@/components/LabHome";
import { getScenarioDefinition, type ScenarioDefinition } from "@/lib/scenarios";
import {
  getFrameAt, PROFILES, simulate,
  type ProfileId, type Scenario, type SimulationResult,
} from "@/lib/simulation";

type Workspace = "build" | "preview" | "session" | "debrief";
type EventItem = { id:number; time:number; type:"run"|"fault"|"observation"; title:string; detail:string };

export default function LabPage(){
  const searchParams=useSearchParams();
  const scenarioId=searchParams.get("scenario");
  if(!scenarioId)return <LabHome/>;
  return <LabWorkbench definition={getScenarioDefinition(scenarioId)}/>;
}

function LabWorkbench({definition}:{definition:ScenarioDefinition}){
  const [scenario,setScenario]=useState<Scenario>(()=>({...definition.scenario}));const [result,setResult]=useState(()=>simulate(definition.scenario));const [workspace,setWorkspace]=useState<Workspace>("build");const [playing,setPlaying]=useState(false);const [time,setTime]=useState(0);const [speed,setSpeed]=useState(1);const [advanced,setAdvanced]=useState(false);const [layers,setLayers]=useState({interceptor:true,target:true,lineOfSight:true});const [comparison,setComparison]=useState<Record<ProfileId,SimulationResult>|null>(null);const [events,setEvents]=useState<EventItem[]>([{id:1,time:0,type:"run",title:"Scenario initialized",detail:`${definition.domain} · ${definition.title} · library ${definition.version}`}]);const [faultArmed,setFaultArmed]=useState(false);const [saved,setSaved]=useState(false);
  const [buildStep,setBuildStep]=useState(0);
  const run=useCallback(()=>{const next=simulate(scenario);setResult(next);setTime(0);setPlaying(true);setWorkspace("session");setComparison(null);setEvents(items=>[...items,{id:Date.now(),time:0,type:"run",title:"Run started",detail:`${definition.domain} · ${PROFILES[scenario.profile].name} · ${scenario.guidance} profile`}])},[definition.domain,scenario]);
  useEffect(()=>{if(!playing)return;let animation=0;let previous=performance.now();let accumulated=0;const tick=(now:number)=>{const delta=(now-previous)/1000;previous=now;accumulated+=delta;if(accumulated>=1/30){const elapsed=accumulated;accumulated=0;setTime(current=>{const next=current+elapsed*speed;if(next>=result.timeOfFlight){setPlaying(false);return result.timeOfFlight}return next})}animation=requestAnimationFrame(tick)};animation=requestAnimationFrame(tick);return()=>cancelAnimationFrame(animation)},[playing,result.timeOfFlight,speed]);
  useEffect(()=>{const keys=(event:KeyboardEvent)=>{if(event.key===" "){event.preventDefault();setPlaying(value=>!value)}if(event.key==="Enter")run();if(event.key==="ArrowRight")setTime(value=>Math.min(result.timeOfFlight,value+.5));if(event.key==="ArrowLeft")setTime(value=>Math.max(0,value-.5))};window.addEventListener("keydown",keys);return()=>window.removeEventListener("keydown",keys)},[result.timeOfFlight,run]);
  const frame=useMemo(()=>getFrameAt(result,time),[result,time]);const validations=["Training objective is defined","Initial geometry is within profile limits","Target trajectory has no timing conflicts","One prepared fault has a valid effect","Report provenance fields are present"];
  const injectFault=()=>{setFaultArmed(false);setEvents(items=>[...items,{id:Date.now(),time,type:"fault",title:"Track quality degraded",detail:"Prepared 8-second sensor-quality fault introduced"}])};
  const addObservation=()=>setEvents(items=>[...items,{id:Date.now(),time,type:"observation",title:"Instructor bookmark",detail:"Decision point marked for debrief"}]);
  const compare=()=>{setComparison({short:simulate(scenario,"short"),medium:simulate(scenario,"medium"),sustained:simulate(scenario,"sustained")});setPlaying(false)};
  const saveReport=()=>{const payload={scenario,result,events,createdAt:new Date().toISOString(),engine:"browser-point-mass-v0.2",profileVersion:"abstract-v0.2",libraryScenario:{id:definition.id,version:definition.version,domain:definition.domain,title:definition.title,scope:definition.scope,targetProfile:definition.targetProfile,theatre:definition.theatre}};localStorage.setItem("vector:last-report",JSON.stringify(payload));setSaved(true)};
  return <main className="lab-shell">
    <header className="lab-header"><Link href="/lab" className="back-link"><ArrowLeft size={15}/>Lab Home</Link><div className="scenario-name"><span>{definition.domain} · Library {definition.version}</span><strong>{scenario.name}</strong></div><nav aria-label="Session lifecycle">{(["build","preview","session","debrief"] as Workspace[]).map(item=><button key={item} className={workspace===item?"active":""} onClick={()=>setWorkspace(item)}>{{build:"Design",preview:"Validate",session:"Conduct",debrief:"Debrief"}[item]}</button>)}</nav><div className="lab-actions"><span><ShieldCheck size={14}/>Educational model</span><button onClick={()=>{saveReport();setSaved(true)}}><Save size={14}/>{saved?"Saved":"Save"}</button><Link href="/report" onClick={saveReport}><FileText size={14}/>Report</Link></div></header>
    <div className="lab-notice"><CircleAlert size={13}/><span>{definition.scope} Public-data approximation; do not read the result as verified weapon performance.</span></div>
    {workspace==="build"?<BuildWorkspace definition={definition} scenario={scenario} setScenario={setScenario} advanced={advanced} setAdvanced={setAdvanced} step={buildStep} setStep={setBuildStep} validate={()=>setWorkspace("preview")}/>:workspace==="preview"?<PreviewWorkspace scenario={scenario} validations={validations} run={run}/>:workspace==="debrief"?<DebriefWorkspace scenario={scenario} result={result} events={events} saveReport={saveReport}/>:<section className="session-layout">
      <aside className="session-left"><div className="session-heading"><span>Session controls</span><strong>Run 01 · Active</strong></div><section><h2>Prepared events</h2><button className={faultArmed?"fault active":"fault"} onClick={()=>setFaultArmed(value=>!value)}><TriangleAlert size={15}/><span><strong>Track-quality degradation</strong><small>8 seconds · trainee-visible</small></span><em>{faultArmed?"ARMED":"PREPARED"}</em></button>{faultArmed&&<button className="inject" onClick={injectFault}>Introduce fault now</button>}</section><section><h2>Instructor tools</h2><button className="tool-button" onClick={addObservation}><Flag size={15}/>Add debrief bookmark</button><button className="tool-button" onClick={()=>setPlaying(false)}><Pause size={15}/>Pause session</button><button className="tool-button" onClick={()=>{setTime(0);setEvents([])}}><RotateCcw size={15}/>Reset run</button></section><section><h2>Run plan</h2><div className="run-file"><span>Baseline</span><strong>RUNNING</strong></div><div className="run-file"><span>Degraded track</span><strong>READY</strong></div><div className="run-file"><span>High manoeuvre</span><strong>READY</strong></div></section></aside>
      <section className="simulation-column"><div className="sim-topline"><div><span>Instructor truth view</span><strong>{PROFILES[scenario.profile].name} · {scenario.guidance}</strong></div><div className="live-metrics"><Metric label="Time" value={`${time.toFixed(1)} s`}/><Metric label="3D separation" value={`${(frame.range/1000).toFixed(1)} km`}/><Metric label="Speed" value={`${Math.round(frame.speed)} m/s`}/><Metric label="Energy index" value={`${Math.round(frame.energy)}%`}/></div></div><div className="scene-wrap"><SimulationScene result={result} time={time} profile={scenario.profile} layers={layers}/><div className="symbol-key"><span><i className="friendly-symbol"/>Launcher</span><span><i className="track-symbol"/>Target</span><span><i className="interceptor-symbol"/>Interceptor</span></div><div className="view-note">Abstract symbols · drag to orbit · scroll to zoom</div></div><Playback result={result} time={time} setTime={setTime} playing={playing} setPlaying={setPlaying} speed={speed} setSpeed={setSpeed}/><div className="telemetry"><div className="telemetry-title"><strong>Flight telemetry</strong><span><i className="speed-line"/>Speed</span><span><i className="energy-line"/>Energy index</span></div><TelemetryChart result={result} time={time}/></div></section>
      <aside className="session-right"><Outcome result={result}/>{comparison?<Comparison data={comparison}/>:<Geometry frame={frame}/>}<section className="right-card"><div className="right-title"><Layers3 size={15}/><strong>View layers</strong><span>THIS VIEW</span></div>{Object.entries({interceptor:"Interceptor path",target:"Target path",lineOfSight:"Line of sight"}).map(([key,label])=><button className="layer-toggle" key={key} onClick={()=>setLayers(value=>({...value,[key]:!value[key as keyof typeof value]}))}>{layers[key as keyof typeof layers]?<Eye size={14}/>:<EyeOff size={14}/>}<span>{label}</span><em>VIEW</em></button>)}</section><button className="compare-button" onClick={compare}><Copy size={14}/>Compare all profiles <span>CURRENT SCENARIO</span></button><div className="explain-card"><Sparkles size={16}/><div><strong>Why this result?</strong><p>{result.outcome==="Intercept"?"The profile retained enough energy to close while the target manoeuvred. Increase range or target demand to test the boundary.":"Closing geometry and manoeuvre demand exceeded the remaining energy. Try a shorter range or a lofted path."}</p></div></div></aside>
    </section>}
  </main>;
}

const AUTHORING_STEPS = ["Intent", "Entities", "Geometry", "Events", "Review"];

function BuildWorkspace({definition,scenario,setScenario,advanced,setAdvanced,step,setStep,validate}:{definition:ScenarioDefinition;scenario:Scenario;setScenario:React.Dispatch<React.SetStateAction<Scenario>>;advanced:boolean;setAdvanced:(value:boolean)=>void;step:number;setStep:(value:number)=>void;validate:()=>void}){
  const update=<K extends keyof Scenario>(key:K,value:Scenario[K])=>setScenario(current=>({...current,[key]:value}));
  const headings=[
    ["What should this scenario teach?","Define the question before choosing the model inputs."],
    ["Who is in the training problem?","Assign abstract roles and capability profiles. These are editable model inputs, not identified real-world assets."],
    ["Set the initial geometry.","Control the starting relationship. Computed range, line-of-sight rate, and energy appear only after you conduct a run."],
    ["Prepare the target response.","Choose target behaviour and training demand before the session begins."],
    ["Review before validation.","Confirm the authored inputs and model scope, then move to validation and prepared run files."],
  ];
  const advance=()=>step===AUTHORING_STEPS.length-1?validate():setStep(step+1);
  return <section className="build-workspace">
    <aside className="build-steps"><span>Authoring steps</span>{AUTHORING_STEPS.map((label,index)=><button className={index===step?"active":""} key={label} onClick={()=>setStep(index)} aria-current={index===step?"step":undefined}><i>{index+1}</i>{label}{index<step&&<Check size={13}/>}</button>)}</aside>
    <div className="builder">
      <header><span>Template starting values · {step+1} of 5 · {AUTHORING_STEPS[step]}</span><h1>{headings[step][0]}</h1><p>{headings[step][1]}</p></header>

      {step===0&&<>
        <label className="field"><span>Scenario name · this scenario</span><input value={scenario.name} onChange={event=>update("name",event.target.value)}/></label>
        <label className="field"><span>Learning objective · this scenario</span><textarea value={scenario.objective} onChange={event=>update("objective",event.target.value)}/></label>
        <div className="guided-options"><span>Starting question · sets this scenario objective</span><button onClick={()=>update("objective","Understand how launch geometry and target manoeuvre affect the result")}><Target size={17}/><strong>Geometry & timing</strong><small>How position, heading, and closure shape the opportunity.</small></button><button onClick={()=>update("objective","Understand how energy changes across direct and lofted paths")}><Gauge size={17}/><strong>Energy management</strong><small>Compare flight profiles and terminal energy.</small></button><button onClick={()=>update("objective","Practice reassessment when track quality is degraded")}><TriangleAlert size={17}/><strong>Decision under uncertainty</strong><small>Introduce a prepared information-quality fault.</small></button></div>
      </>}

      {step===1&&<section className="authoring-section">
        <div className="entity-role-grid"><article><span>FRIENDLY ROLE</span><strong>{definition.blue}</strong><p>Launcher / interceptor origin</p></article><article><span className="hostile-label">OPPOSING ROLE</span><strong>{definition.red}</strong><p>{definition.targetProfile}</p></article></div>
        <div className="section-label"><span>Interceptor profile · selected asset</span><small>Series colors compare profiles; they do not indicate affiliation</small></div>
        <div className="profile-choice">{(Object.keys(PROFILES) as ProfileId[]).map(id=><button key={id} className={scenario.profile===id?"active":""} onClick={()=>update("profile",id)}><i className={`profile-${id}`}/><strong>{PROFILES[id].short}</strong><small>{PROFILES[id].name}</small></button>)}</div>
        <div className="advanced-grid"><Range label="Launcher speed" value={scenario.launcherSpeed} min={0} max={450} step={5} unit="m/s" onChange={value=>update("launcherSpeed",value)}/><Range label="Target speed" value={scenario.targetSpeed} min={0} max={450} step={5} unit="m/s" onChange={value=>update("targetSpeed",value)}/></div>
      </section>}

      {step===2&&<section className="authoring-section">
        <div className="compact-controls"><Range label="Launch range" value={scenario.range/1000} min={5} max={120} unit="km" onChange={value=>update("range",value*1000)}/><Range label="Launch altitude" value={scenario.altitude} min={0} max={15000} step={10} unit="m" onChange={value=>update("altitude",value)}/><Range label="Target altitude Δ" value={scenario.targetDelta} min={-12000} max={12000} step={10} unit="m" onChange={value=>update("targetDelta",value)}/></div>
        <div className="geometry-choice"><button className={scenario.guidance==="direct"?"active":""} onClick={()=>update("guidance","direct")}><strong>Direct path</strong><small>Point-mass pursuit without a commanded loft.</small></button><button className={scenario.guidance==="loft"?"active":""} onClick={()=>update("guidance","loft")}><strong>Lofted path</strong><small>Adds a simplified altitude arc to the trajectory.</small></button></div>
        <button className="advanced-toggle" onClick={()=>setAdvanced(!advanced)}><Settings2 size={14}/>{advanced?"Hide additional geometry":"Show additional geometry"}</button>
        {advanced&&<div className="advanced-grid"><Range label="Aspect angle" value={scenario.aspect} min={0} max={180} step={5} unit="°" onChange={value=>update("aspect",value)}/><Range label="Environmental loss" value={scenario.wind} min={0} max={40} step={1} unit="index" onChange={value=>update("wind",value)}/></div>}
      </section>}

      {step===3&&<section className="authoring-section">
        <div className="event-choice"><button className={scenario.maneuver==="steady"?"active":""} onClick={()=>update("maneuver","steady")}><strong>Steady course</strong><small>No commanded target manoeuvre.</small></button><button className={scenario.maneuver==="break"?"active":""} onClick={()=>update("maneuver","break")}><strong>Defensive break</strong><small>One turn begins after five model seconds.</small></button><button className={scenario.maneuver==="weave"?"active":""} onClick={()=>update("maneuver","weave")}><strong>Weaving turn</strong><small>Alternating simplified turn demand.</small></button></div>
        <Range label="Target manoeuvre demand · selected target" value={scenario.targetG} min={0} max={9} step={.5} unit="g" onChange={value=>update("targetG",value)}/>
        <article className="prepared-event"><TriangleAlert size={17}/><div><span>PREPARED INSTRUCTOR EVENT</span><strong>Track-quality degradation</strong><p>An eight-second information-quality fault can be introduced during Conduct. It affects the training record, not the current point-mass physics.</p></div><em>READY</em></article>
      </section>}

      {step===4&&<section className="review-inputs">
        <div><span>Intent</span><strong>{scenario.name}</strong><p>{scenario.objective}</p><button onClick={()=>setStep(0)}>Edit intent</button></div>
        <div><span>Entities</span><strong>Friendly: {definition.blue} · Opposing: {definition.red}</strong><p>{PROFILES[scenario.profile].name} · target {scenario.targetSpeed} m/s</p><button onClick={()=>setStep(1)}>Edit entities</button></div>
        <div><span>Geometry</span><strong>{scenario.range/1000} km · {scenario.guidance}</strong><p>{scenario.altitude} m launch altitude · {scenario.aspect}° aspect</p><button onClick={()=>setStep(2)}>Edit geometry</button></div>
        <div><span>Events</span><strong>{scenario.maneuver} · {scenario.targetG} g</strong><p>Track-quality degradation prepared for instructor use.</p><button onClick={()=>setStep(3)}>Edit events</button></div>
        <aside><Check size={16}/><p>Inputs are complete. Validation checks model scope, timing conflicts, and report provenance before Conduct.</p></aside>
      </section>}

      <footer className="builder-actions"><span>Design input · this scenario</span><div>{step>0&&<button className="back-action" onClick={()=>setStep(step-1)}>Back</button>}<button onClick={advance}>{step===4?<><Check size={15}/>Validate scenario</>:<>Next: {AUTHORING_STEPS[step+1]}</>}</button></div></footer>
    </div>
    <aside className="builder-summary"><span>Live scenario summary</span><dl><dt>Library template</dt><dd>{definition.id} · {definition.version}</dd><dt>Mission set</dt><dd>{definition.domain}</dd><dt>Friendly role</dt><dd>{definition.blue}</dd><dt>Opposing role</dt><dd>{definition.red}</dd><dt>Question</dt><dd>{scenario.objective}</dd><dt>Profile</dt><dd>{PROFILES[scenario.profile].name}</dd><dt>Geometry</dt><dd>{scenario.range/1000} km · {scenario.altitude} m</dd><dt>Target profile</dt><dd>{definition.targetProfile}</dd><dt>Prepared fault</dt><dd>Track quality degradation</dd></dl><div><CircleHelp size={15}/><p>{definition.scope}</p></div></aside>
  </section>;
}

function PreviewWorkspace({scenario,validations,run}:{scenario:Scenario;validations:string[];run:()=>void}){return <section className="preview-workspace"><header><span>Scenario preview</span><h1>Ready to conduct</h1><p>Review what the participant will see and confirm that the session can be reproduced.</p></header><div className="preview-grid"><article><h2>Briefing</h2><strong>{scenario.name}</strong><p>{scenario.objective}</p><dl><dt>Environment</dt><dd>Day · moderate visibility</dd><dt>Entities</dt><dd>1 launcher · 1 target</dd><dt>Run duration</dt><dd>Up to 100 seconds</dd></dl></article><article><h2>Validation</h2>{validations.map(item=><div className="validation" key={item}><Check size={14}/>{item}</div>)}</article><article><h2>Prepared run files</h2><div className="preview-run"><span>01</span><div><strong>Baseline</strong><small>Default geometry and seed</small></div><em>READY</em></div><div className="preview-run"><span>02</span><div><strong>Degraded track</strong><small>8-second information fault</small></div><em>READY</em></div><div className="preview-run"><span>03</span><div><strong>High manoeuvre</strong><small>Target turn demand increased</small></div><em>READY</em></div></article></div><button className="conduct-button" onClick={run}><Play size={16}/>Conduct session</button></section>}

function DebriefWorkspace({scenario,result,events,saveReport}:{scenario:Scenario;result:SimulationResult;events:EventItem[];saveReport:()=>void}){return <section className="debrief-workspace"><header><span>Debrief</span><h1>{scenario.name}</h1><p>Review the outcome in the context of the scenario, interventions, and information available.</p></header><div className="debrief-grid"><article className="debrief-outcome"><span>Outcome</span><h2>{result.outcome}</h2><p>{result.reason}</p><div><Metric label="Closest approach" value={`${Math.round(result.closestApproach)} m`}/><Metric label="Time of flight" value={`${result.timeOfFlight.toFixed(1)} s`}/><Metric label="End speed" value={`${Math.round(result.endSpeed)} m/s`}/></div></article><article className="event-log"><h2>Session timeline</h2>{events.length?events.map(event=><div key={event.id}><time>{event.time.toFixed(1)} s</time><i className={event.type}/><span><strong>{event.title}</strong><small>{event.detail}</small></span></div>):<p>No instructor events were recorded in this run.</p>}</article><article className="debrief-notes"><h2>Instructor assessment</h2><textarea defaultValue="The participant recognized the changing geometry and reassessed after track degradation. Review the timing of the final decision."/><label><span>Recommendation</span><select defaultValue="repeat"><option value="complete">Objective met</option><option value="repeat">Repeat with variation</option><option value="remedial">Remedial session</option></select></label><Link href="/report" onClick={saveReport}><FileText size={15}/>Generate report</Link></article></div></section>}

function Range({label,value,min,max,step=1,unit,onChange}:{label:string;value:number;min:number;max:number;step?:number;unit:string;onChange:(value:number)=>void}){return <label className="range-field"><span>{label}</span><output>{Number.isInteger(value)?value:value.toFixed(1)} <small>{unit}</small></output><input type="range" value={value} min={min} max={max} step={step} onChange={event=>onChange(Number(event.target.value))}/></label>}
function Playback({result,time,setTime,playing,setPlaying,speed,setSpeed}:{result:SimulationResult;time:number;setTime:(value:number)=>void;playing:boolean;setPlaying:(value:boolean)=>void;speed:number;setSpeed:(value:number)=>void}){return <div className="playback"><button onClick={()=>setTime(0)}><RotateCcw size={14}/></button><button className="play" onClick={()=>setPlaying(!playing)}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><input aria-label="Session timeline" type="range" min={0} max={result.timeOfFlight||1} step={.1} value={time} onChange={event=>setTime(Number(event.target.value))}/><span>{time.toFixed(1)} / {result.timeOfFlight.toFixed(1)} s</span><div>{[.5,1,2,4].map(value=><button key={value} className={speed===value?"active":""} onClick={()=>setSpeed(value)}>{value}×</button>)}</div></div>}
function Outcome({result}:{result:SimulationResult}){return <section className={`outcome ${result.outcome==="Intercept"?"success":"caution"}`}><span>Model outcome</span><h2>{result.outcome}</h2><p>{result.reason}</p><div><Metric label="Closest" value={`${Math.round(result.closestApproach)} m`}/><Metric label="TOF" value={`${result.timeOfFlight.toFixed(1)} s`}/><Metric label="End speed" value={`${Math.round(result.endSpeed)} m/s`}/><Metric label="Peak demand" value={`${result.peakDemand.toFixed(1)} g`}/></div></section>}
function Geometry({frame}:{frame:ReturnType<typeof getFrameAt>}){return <section className="right-card"><div className="right-title"><Target size={15}/><strong>Relative geometry</strong><span>{frame.phase}</span></div><div className="scope"><i/><b/><small>Diagram · not sensor field-of-view</small></div><div className="geometry-data"><Metric label="LOS rate" value={`${frame.losRate.toFixed(3)} rad/s`}/><Metric label="3D separation" value={`${(frame.range/1000).toFixed(1)} km`}/><Metric label="Energy index" value={`${Math.round(frame.energy)}%`}/></div><p className="derived-note">Computed by the current abstract run. Energy index is normalized interceptor speed—not physical total energy.</p></section>}
function Comparison({data}:{data:Record<ProfileId,SimulationResult>}){return <section className="right-card"><div className="right-title"><Gauge size={15}/><strong>Profile comparison</strong></div><div className="comparison">{(Object.keys(data) as ProfileId[]).map(id=><div key={id}><strong><i className={`profile-${id}`}/>{PROFILES[id].short}</strong><span>{data[id].outcome}</span><span>{Math.round(data[id].closestApproach)} m</span><span>{data[id].timeOfFlight.toFixed(1)} s</span></div>)}</div></section>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
